sqlservers:
  - alias: demo_cdc
    database: demo_cdc
    schema: dbo                  # schema default das tabelas, se não for informado em cada uma
    secretName: sqlserver-origem-demo_cdc
    maxTablesPerSource: 5        # até 5 tabelas por source
    maxRowsPerSource: 50000000   # até 50M de linhas somadas por source
    tables:
      - name: Clientes


  - alias: demo_cdc_2
    database: demo_cdc_2
    schema: dbo                  # schema default das tabelas, se não for informado em cada uma
    secretName: sqlserver-origem-demo_cdc_2
    maxTablesPerSource: 5        # até 5 tabelas por source
    maxRowsPerSource: 50000000   # até 50M de linhas somadas por source
    tables:
      - name: Clientes

  - alias: demo_cdc_3
    database: demo_cdc_3
    schema: dbo                  # schema default das tabelas, se não for informado em cada uma
    secretName: sqlserver-origem-demo_cdc_3
    maxTablesPerSource: 5        # até 5 tabelas por source
    maxRowsPerSource: 50000000   # até 50M de linhas somadas por source
    tables:
      - name: Clientes

  - alias: demo_cdc_4
    database: demo_cdc_4
    schema: dbo                  # schema default das tabelas, se não for informado em cada uma
    secretName: sqlserver-origem-demo_cdc_4
    maxTablesPerSource: 5        # até 5 tabelas por source
    maxRowsPerSource: 30   # até 50M de linhas somadas por source
    tables:
      - name: ClientesAtivos
      - name: ClientesAtivosDados
      - name: ClientesAtivosDadosValidos
      - name: ClientesAtivosD
      - name: ClientesAtivosDV
      - name: ClientesAtivosDVA
